version: '3.7'
services:
  mongodb-Cont:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ivan
      MONGO_INITDB_ROOT_PASSWORD: piper159951
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_cont:/data/db

volumes:
  mongodb_data_cont: